#!/usr/bin/env bash

export POSIXLY_CORRECT=yes
export LC_NUMERIC=en_US.UTF-8

set -u # FIXME after

############################## FUNCTIONS ##############################
help() {
    echo "Usage: corona [-h] [FILTERS] [COMMAND] [LOG [LOG2 [...]]"
    echo ""
    echo "   -h              prints help with instructions, and script terminates"
    echo ""
    echo "COMMAND:"
    echo "   infected          prints number of infected"
    echo "   merge             merges multiple input files into one, keeping the original order"
    echo "   gender            prints number of infected for each gender"
    echo "   age               prints number of infected for each age group"
    echo "   daily             prints number of infected for each day"
    echo "   monthly           prints number of infected for each month"
    echo "   yearly            prints number of infected for each year"
    echo "   countries         prints number of infected for each country (CZ not included)"
    echo "   districts         prints number of infected for each district"
    echo "   regions           prints number of infected for each region"
    echo ""
    echo "FILTERS:"
    echo "   -a DATETIME       after: records after given date (included)"
    echo "   -b DATETIME       before: records before given date (included)"
    echo "   -g GENDER         records with given GENDER: M - male (muzi), Z - female (zeny)"
    echo "   -s [WIDTH]        with commands gender, age, daily, monthly, yearly, countries"
    echo "                     districts and regions the data are displayed in a histogram."
    echo "                     WIDTH (optional positive number) sets width of the histogram."
    echo "                     If not given, with is set to default (see documentation)"
    echo "   -d DISTRICT_FILE  for command disrticts prints, instead of the LAU 1 code of"
    echo "                     a district, its proper name. DISTRICT_FILE contains the"
    echo "                     code to name mapping"
    echo "   -r REGIONS_FILE   for command regions prints instead of the NUTS 3 code of"
    echo "                     a region, its proper name. REGIONS_FILE contains the"
    echo "                     code to name mapping"
    echo ""
    echo "Script filters records of people infected by COVID-19."
    echo "If no commands or filters are given, script prints records to standart output"
    echo "Script is able to process .gz or .bz2 files"
    echo "If no files (LOG, LOG2, ...) are given, sript expects records from standart input"
    echo ""
}

search_commands() {
    for C in $2; do
        if [ "$C" = $1 ]; then
            return 0
        fi
    done
    return 1
}

############################## DATA ##############################
# COMMANDS="infected merge gender age daily monthly yearly countries districts regions"
COMMAND=""

# FILTERS
A_FILTER=""
B_FILTER=""
G_FILTER=""
S_FILTER=""
D_FILTER=""
R_FILTER=""

# filters parameters
A_DATETIME=""
B_DATETIME=""
GENDER=""
WIDTH=""    # c FIXME but youll need [ -n "$WIDTH" ]
DISTRICT_FILE=""
REGIONS_FILE=""

############################## MAIN ##############################
while [ "$#" -gt 0 ]; do
    case "$1" in
    infected | merge | gender | age | daily | monthly | yearly | countries | districts | regions)
        COMMAND=$1
        ;;
    -a)
        A_FILTER=1
        A_DATETIME=$2
        shift
        ;;
    -b)
        B_FILTER=1
        B_DATETIME=$2
        shift
        ;;
    -g)
        G_FILTER=1
        GENDER=$2
        shift
        ;;
    -s)
        S_FILTER=1
        read WIDTH <<< "$(echo "$2" | awk '$0 ~/^[0-9]+$/ { print $0 }')"
        if [ -n "$WIDTH" ]; then
            shift
        fi
        ;;
    -d)
        D_FILTER=1
        DISTRICT_FILE=$2
        shift
        ;;
    -r)
        R_FILTER=1
        REGIONS_FILE=$2
        shift
        ;;
    -h)
        help
        exit 0
        ;;
    *)
        ;;
    esac
    shift
done

echo "-a $A_FILTER and $A_DATETIME"
echo "-b $B_FILTER and $B_DATETIME"
echo "-g $G_FILTER and $GENDER"
echo "-s $S_FILTER and $WIDTH"
echo "Command: $COMMAND"
